name: CI

on: [push]

jobs:
  ###############
  # Lint & Test
  ###############
  tests:
    name: Tests
    runs-on: ubuntu-latest
    # needs: linters
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_test
      NODE_ENV: test
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        ports: ['5432:5432']
        # Make sure the database is ready before we use it
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Node
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      # Yarn cache/install
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v2.1.0
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --frozen-lockfile

      # Setup & configure database
      - name: Setup test database
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost/myapp_test
        run: |
          yarn db:migrate

      # Build app and generate types
      - name: Build App
        run: yarn build

      # Lint Code
      - name: ESLint
        run: yarn lint

      # Jest Tests (API/Frontend)
      - name: Run Jest Tests (API & Frontend)
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:postgres@localhost/myapp_test
        run: yarn test:ci
